# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

logo: assets/images/seedling-logo-blue.svg
title: Seedling
description: >- # ignore newlines until next yaml entry
  Seedling is a first-language digital learning tool for adults;
  a collection of literacy exercises that bundled content can make use of
  to provide lessons to learners unfamiliar with reading
  the particular content language.

atom_feed:
  hide: true

footer:
  links:
    - label: Privacy policy
      url: "/privacy-policy"
      icon: none

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: sidebar-documentation
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

date_format: "%Y %B %-d"

social:
  type: Organization
  name: Nodepa
  links:
    - https://nodepa.org

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
repository: nodepa/seedling

domain: globalseedling.com
url: https://globalseedling.com
baseurl:

include:
  - _pages

search: true
search_full_content: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
